[project]
name = "all-in-one-seller-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "idna>=3.11",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "ruff>=0.14.10",
    "wrapper-tls-requests>=1.1.9",
]
